# Generated by Django 4.1 on 2022-09-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('motor', models.FloatField()),
                ('modelo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='camioneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('motor', models.FloatField()),
                ('modelo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('cilindrada', models.FloatField()),
                ('modelo', models.DateField()),
            ],
        ),
    ]
