# Generated by Django 4.1 on 2022-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='camioneta',
            name='modelo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moto',
            name='modelo',
            field=models.IntegerField(),
        ),
    ]
