# Generated by Django 4.1 on 2022-09-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0002_alter_auto_modelo_alter_camioneta_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='motor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='camioneta',
            name='motor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cilindrada',
            field=models.IntegerField(),
        ),
    ]
